### ISSUE TITLE
passwords encryption 

### ISSUE THREAD

**Issue by Hans-0** [SBFspot/sbfspot-config#40]
Why are the passwords not encrypted/hashed in the configfile SBFspot.cfg?
I don't understand why the passwords are readable in de config.

**Comment by sbf-** [comment]
Because it started as (and still is) a hobby project and I didn't need it.
Hashing is unusable here as the password should be "unhashed" (which is impossible) to get the plain text password to be able to login.
Encryption is possible, but with the source code available it is a piece of cake to decrypt it.
If you automate SMA's SunnyExplorer the password is also in plain text.
But, it's a valid question and after 12y you're the first to ask ;-)
